server.port:  8888

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri:  https://github.com/manishthakur/spring-cloud-config.git
          #uri:  file://C:/java/projects/learnings/configrepo
          skipSslValidation: true
          default-label: master

















