server.port:  8888

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri:  https://github.com/manishthakur/spring-cloud-config.git
          skipSslValidation: true
          default-label: master
          clone-on-start: true













